### ISSUE TITLE
Crashes after pressing enter on ready prompt

### ISSUE THREAD

**Issue by 0x0000000FF1CE** [vaezim/Online-Chess-cheater-Bot#1]
ignore and close im retarded

**Comment by vaezim** [comment]
You're right about the crashes. I'm going to restructure the project in the following week. Thanks.

**Comment by 0x0000000FF1CE** [comment]
Hey man I can't figure out how to get it to recognise the engine I have messed around with changing the engine path but getting this error everytime

Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Online-Chess-cheater-Bot-main\Online-Chess-cheater-Bot-main\lichess\lichessCheater.py", line 65, in <module>
    stockfish = Stockfish(path=ENGINE_PATH, depth=18)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\stockfish\models.py", line 47, in __init__
    self._stockfish = subprocess.Popen(
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1493, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
Exception ignored in: <function Stockfish.__del__ at 0x0000025FB5567B00>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\stockfish\models.py", line 757, in __del__
    if self._stockfish.poll() is None:
       ^^^^^^^^^^^^^^^
AttributeError: 'Stockfish' object has no attribute '_stockfish'

**Comment by vaezim** [comment]
put it where the code file is and edit the line
ENGINE_PATH = r"stockfish_15_win_x64_popcnt\stockfish_15_x64_popcnt"

**Comment by 0x0000000FF1CE** [comment]
Thanks and lastly I am now getting this error , 
 File "C:\Users\Administrator\Downloads\Online-Chess-cheater-Bot-main\Online-Chess-cheater-Bot-main\lichess\lichessCheater.py", line 73, in <module>
    oppMove = driver.find_element(By.XPATH,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: /html/body/div[1]/main/div/rm6/l4x/u8t[1]
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:180:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:392:5
element.find/</<@chrome://remote/content/marionette/element.sys.mjs:275:16

**Comment by vaezim** [comment]
Those will be fixed.

**Comment by 0x0000000FF1CE** [comment]
Chess.com version works just fine so will use that for now , thanks!
